# Generated by Django 6.0.1 on 2026-02-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like_and_rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
