# Generated by Django 6.0.1 on 2026-02-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like_and_rating', '0002_productreview_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='active',
            new_name='is_active',
        ),
    ]
