# Generated by Django 6.0.1 on 2026-02-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productlike_productreview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProductLike',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
